cc_library(
    name = "input",
    srcs = [
        "input.cc",
        "input.h",
    ],
    copts = [
        "-Wall",
        "-Werror",
        "-pedantic",
    ],
    visibility = [":__subpackages__"],
    deps = [
        "@com_google_absl//absl/base",
        "@com_google_absl//absl/strings",
    ],
)
